import requests
import json
import re

# CHANGED: Import dedicated HuggingFace classifier instead of relying on LLM tags
import emotion_classifier

# ─── Keyword-based intent grounding ──────────────────────────────────────────
_NOT_INTERESTED_SIGNALS = [
    "not interested", "no thanks", "no thank you", "don't call", "do not call",
    "remove me", "take me off", "stop calling", "busy", "not now", "bad time",
    "already have", "not looking", "no need", "not needed", "don't need",
    "can't talk", "cannot talk", "call later", "no no", "nope", "nah",
    "i'm good", "i am good", "we're good", "we are good", "please don't",
    "please stop", "goodbye", "bye bye", "hang up", "wrong number"
]

_CALLBACK_SIGNALS = [
    "call me later", "call back", "callback", "try again", "another time",
    "not right now", "in a meeting", "call tomorrow", "call next week",
    "reach me later", "ping me later", "send an email", "send me details",
    "send me info", "whatsapp me", "text me"
]

_INTERESTED_SIGNALS = [
    "tell me more", "interested", "sounds good", "go ahead", "sure",
    "yes please", "i'd like", "i would like", "how much", "what's the price",
    "what is the price", "pricing", "how does it work", "when can", "sign me up",
    "let's do it", "let me know more", "i want", "please continue"
]


def _classify_intent_from_user(user_text: str) -> str | None:
    """
    Returns a definitive intent if user's text has strong keyword signals.
    Returns None if ambiguous — defer to LLM result.
    Priority: Not Interested > Callback > Interested
    """
    lower = user_text.lower()
    for phrase in _NOT_INTERESTED_SIGNALS:
        if phrase in lower:
            return "Not Interested"
    for phrase in _CALLBACK_SIGNALS:
        if phrase in lower:
            return "Callback"
    for phrase in _INTERESTED_SIGNALS:
        if phrase in lower:
            return "Interested"
    return None


def _clean_reply(text: str) -> str:
    """Strips Intent: lines and any inline [INTENT:X] markers from spoken reply."""
    lines = [
        l for l in text.split('\n')
        # CHANGED: Only strip Intent: lines, not Emotion: (no longer in LLM output)
        if not re.match(r'^\s*intent\s*:', l, re.IGNORECASE)
    ]
    cleaned = '\n'.join(lines).strip()
    # CHANGED: Only strip [INTENT:X] tags (no more [EMOTION:X] tags to remove)
    cleaned = re.sub(r'\[INTENT:.*?\]', '', cleaned, flags=re.IGNORECASE).strip()
    cleaned = re.sub(r'\.\s*Intent\s*:\s*\S+\s*$', '.', cleaned, flags=re.IGNORECASE).strip()
    cleaned = re.sub(r'\s*Intent\s*:\s*\S+\s*$', '', cleaned, flags=re.IGNORECASE).strip()
    return cleaned.strip()


def _normalise_intent(raw: str) -> str:
    lower = raw.lower()
    if "not interested" in lower or "not_interested" in lower:
        return "Not Interested"
    if "interested" in lower:
        return "Interested"
    if "callback" in lower:
        return "Callback"
    if "objection" in lower:
        return "Objection"
    return "Neutral"


# REMOVED: _normalise_emotion() — no longer needed, emotion comes from HuggingFace classifier


# ─── Emotional intelligence system prompts ────────────────────────────────────

# CHANGED: Removed [EMOTION:X][INTENT:Y] tag instructions — emotion is now
# detected by HuggingFace classifier on the USER's text, not generated by Nandita.
# Kept all CRITICAL ROLEPLAY INSTRUCTIONS and response strategy rules.
_EMOTION_RULES = """
CRITICAL ROLEPLAY INSTRUCTIONS:
- You are CURRENTLY on a LIVE voice call with a human prospect.
- NEVER break character. NEVER mention you are an AI. 
- NEVER offer to "help write a script" or "come up with ideas". 
- Respond directly to what the user says as if you are the person making the sales call.
- Start speaking immediately in character.

EMOTIONAL RESPONSE STRATEGY:
You will receive context about the caller's emotional state. Adapt your tone accordingly:
- ANGRY/FRUSTRATED → Immediately apologize, lower energy, de-escalate. 
  Do NOT pitch. Say: "I completely understand, I'm so sorry to interrupt your time."
- EXCITED/INTERESTED → Match their energy! Be enthusiastic. Move toward the close.
  "That's great to hear! Can I ask — when would be a good time to..."
- CONFUSED → Slow down. Use simpler words. One piece of info at a time.
  "Let me explain that more simply..."
- HESITANT → Identify their specific objection and address it directly.
  "It sounds like you might have concerns about X — can I address that?"
- DISINTERESTED/SAD → Be empathetic. Don't push. Offer an alternative.
  "I completely understand. Would it be okay if I sent you some info instead?"
- NEUTRAL/HAPPY → Engage warmly. Ask an open question to draw them in.

CONVERSATION RULES:
1. Keep responses under 3 sentences maximum
2. Speak exactly the words you want to say out loud to the customer.
3. Always end with either a question OR a clear next step
4. Never repeat the same phrase twice in a conversation
5. If user says "not interested" twice → gracefully end the call:
   "Absolutely, I respect that completely. Have a wonderful day!" then output [END_CALL]
6. If user asks to call back → confirm and output [CALLBACK]
"""


def get_streaming_system_prompt(business_context=None, script=None, knowledge_base=None) -> str:
    """
    CHANGED: Streaming prompt — only [INTENT:Y] tag at end of reply.
    Emotion is now classified separately via HuggingFace on the user's text.
    """
    base = (
        "You are Nandita, an emotionally intelligent female tele-calling sales agent on a live phone call. "
        "You mirror the caller's energy level and adapt your tone to their emotional state. "
        "You are warm, natural, and human-like — never robotic.\n\n"
        + _EMOTION_RULES
    )
    if business_context or script or knowledge_base:
        base += "\n--- CAMPAIGN CONTEXT ---\n"
        if business_context:
            base += f"Business Context: {business_context}\n"
        if script:
            base += f"Agent Script / Goal: {script}\n"
        if knowledge_base:
            base += f"Knowledge Base / FAQs: {knowledge_base}\n"
        base += "\n"

    # CHANGED: Only [INTENT:Y] tag now — no [EMOTION:X] tag
    base += (
        "OUTPUT FORMAT — append ONLY this tag at the very end of your spoken reply:\n"
        "[INTENT:Y]\n\n"
        "Where Y is one of: INTERESTED, NOT_INTERESTED, CALLBACK, NEUTRAL, OBJECTION\n\n"
        "Example:\n"
        "I completely understand! Could I ask — what specifically caught your interest? "
        "[INTENT:INTERESTED]\n\n"
        "IMPORTANT: The tag must be at the very end. Never put it in the middle of your reply."
    )
    return base


def get_system_prompt(business_context=None, script=None, knowledge_base=None) -> str:
    """
    CHANGED: Non-streaming prompt (Twilio path) — structured Reply:/Intent: format only.
    Emotion: line removed — emotion is classified from user text by HuggingFace.
    """
    base = (
        "You are Nandita, an emotionally intelligent female tele-calling sales agent on a live phone call. "
        "You mirror the caller's energy level and adapt your tone to their emotional state. "
        "You are warm, natural, and human-like — never robotic.\n\n"
        + _EMOTION_RULES
    )
    if business_context or script or knowledge_base:
        base += "\n--- CAMPAIGN CONTEXT ---\n"
        if business_context:
            base += f"Business Context: {business_context}\n"
        if script:
            base += f"Agent Script / Goal: {script}\n"
        if knowledge_base:
            base += f"Knowledge Base / FAQs: {knowledge_base}\n"
        base += "\n"

    # CHANGED: Removed "Emotion:" line from structured output format
    base += (
        "STRICT OUTPUT FORMAT — use exactly these two lines in order:\n"
        "Reply: <your 1-3 sentence spoken response only — no tags here>\n"
        "Intent: <INTERESTED|NOT_INTERESTED|CALLBACK|NEUTRAL|OBJECTION>\n\n"
        "Example:\n"
        "Reply: I completely understand and I sincerely apologize for interrupting. "
        "Could I take just 30 seconds, or would you prefer I call back at a better time?\n"
        "Intent: NEUTRAL"
    )
    return base


# ─── Streaming AI response ────────────────────────────────────────────────────

def get_ai_response_streaming(
    prompt: str,
    context: list,
    business_context=None,
    script=None,
    knowledge_base=None
):
    """
    Generator streaming sentences from Ollama in real-time.
    CHANGED: Emotion is now classified from USER's text via HuggingFace (not parsed from LLM tags).
    Yields:
      {"type": "sentence", "text": str}
      {"type": "intent",   "intent": str, "emotion": str, "full_reply": str}
      {"type": "error",    "error": str}
    """
    url = "http://127.0.0.1:11434/api/chat"
    system_prompt = get_streaming_system_prompt(business_context, script, knowledge_base)
    messages = [{"role": "system", "content": system_prompt}] + context + [{"role": "user", "content": prompt}]

    payload = {
        "model": "llama3.2:latest",
        "messages": messages,
        "stream": True,
        "temperature": 0.7
    }

    # CHANGED: Classify caller emotion from USER's text using HuggingFace classifier
    # This runs in parallel with the LLM streaming (called before the request below)
    detected_emotion = emotion_classifier.classify_emotion(prompt)

    try:
        response = requests.post(url, json=payload, stream=True, timeout=30)
        full_reply = ""
        sentence_buffer = ""

        for line in response.iter_lines():
            if not line:
                continue
            try:
                chunk_data = json.loads(line)
            except Exception:
                continue

            token = chunk_data.get("message", {}).get("content", "")
            if not token:
                if chunk_data.get("done"):
                    break
                continue

            full_reply += token
            sentence_buffer += token

            # Yield complete sentences the moment they form
            if any(p in sentence_buffer for p in ['. ', '! ', '? ', '.\n', '!\n', '?\n']):
                parts = re.split(r'(?<=[.!?])\s+', sentence_buffer)
                for sentence in parts[:-1]:
                    # CHANGED: Only strip [INTENT:X] tags (no more [EMOTION:X] tags)
                    clean = re.sub(r'\[INTENT:.*?\]', '', sentence, flags=re.IGNORECASE).strip()
                    if clean and len(clean) > 3:
                        yield {"type": "sentence", "text": clean}
                sentence_buffer = parts[-1]

        # Yield remaining buffer
        if sentence_buffer.strip():
            # CHANGED: Only strip [INTENT:X] tags
            clean = re.sub(r'\[INTENT:.*?\]', '', sentence_buffer, flags=re.IGNORECASE).strip()
            if clean and len(clean) > 3:
                yield {"type": "sentence", "text": clean}

        # CHANGED: Extract only [INTENT:Y] from LLM output (emotion comes from HuggingFace)
        intent_match = re.search(r'\[INTENT:(.*?)\]', full_reply, re.IGNORECASE)
        raw_intent = intent_match.group(1).strip() if intent_match else "NEUTRAL"
        clean_intent = _normalise_intent(raw_intent)

        # Keyword grounding override
        keyword_intent = _classify_intent_from_user(prompt)
        final_intent = keyword_intent if keyword_intent is not None else clean_intent

        # CHANGED: emotion field now comes from HuggingFace classifier, not LLM tags
        yield {
            "type": "intent",
            "intent": final_intent,
            "emotion": detected_emotion,  # CHANGED: from HuggingFace, not LLM
            "full_reply": full_reply
        }

    except requests.exceptions.ConnectionError:
        yield {"type": "error", "error": "OLLAMA_OFFLINE"}
    except requests.exceptions.Timeout:
        yield {"type": "error", "error": "OLLAMA_TIMEOUT"}
    except Exception as e:
        yield {"type": "error", "error": str(e)}


# ─── Non-streaming AI response (Twilio path) ─────────────────────────────────

def generate_ai_response(
    prompt: str,
    context: list,
    business_context=None,
    script=None,
    knowledge_base=None
) -> dict:
    url = "http://127.0.0.1:11434/api/chat"
    system_prompt = get_system_prompt(business_context, script, knowledge_base)
    messages = [{"role": "system", "content": system_prompt}] + context + [{"role": "user", "content": prompt}]

    payload = {
        "model": "llama3.2:latest",
        "messages": messages,
        "stream": False,
        "temperature": 0.7
    }

    # CHANGED: Classify caller emotion from USER's text using HuggingFace classifier
    detected_emotion = emotion_classifier.classify_emotion(prompt)

    try:
        response = requests.post(url, json=payload, timeout=30)
        if response.status_code == 200:
            response_text = response.json().get('message', {}).get('content', '')
            raw_reply = response_text
            raw_intent = "NEUTRAL"

            # CHANGED: Parse only Reply:/Intent: format (Emotion: line removed from prompt)
            reply_match = re.search(r'Reply:\s*(.+?)(?=Intent:|$)', response_text, re.DOTALL | re.IGNORECASE)
            intent_match = re.search(r'Intent:\s*(.+)', response_text, re.IGNORECASE)

            if reply_match:
                raw_reply = reply_match.group(1).strip()
            if intent_match:
                raw_intent = intent_match.group(1).strip()

            clean_reply_text = _clean_reply(raw_reply)
            clean_intent = _normalise_intent(raw_intent)

            # Keyword grounding overrides LLM intent when strong signal present
            keyword_intent = _classify_intent_from_user(prompt)
            final_intent = keyword_intent if keyword_intent is not None else clean_intent

            return {
                "reply": clean_reply_text,
                "intent": final_intent,
                "emotion": detected_emotion,  # CHANGED: from HuggingFace classifier
                "raw": response_text,
                "error": None
            }
        else:
            return {
                "reply": "Ollama connection failed",
                "intent": "Error",
                "emotion": detected_emotion,  # CHANGED: still return HuggingFace emotion
                "raw": response.text,
                "error": "AI_ERROR"
            }

    except requests.exceptions.ConnectionError:
        return {"reply": None, "intent": "Neutral", "emotion": "NEUTRAL", "error": "OLLAMA_OFFLINE"}
    except requests.exceptions.Timeout:
        return {"reply": None, "intent": "Neutral", "emotion": "NEUTRAL", "error": "OLLAMA_TIMEOUT"}
    except Exception as e:
        return {"reply": None, "intent": "Neutral", "emotion": "NEUTRAL", "error": f"AI_ERROR: {str(e)}"}


# ─── End-of-call QA scoring ───────────────────────────────────────────────────

def score_call(transcript: list) -> dict:
    """
    Evaluates full transcript. Returns {"summary", "lead_score", "final_intent"}.
    """
    url = "http://127.0.0.1:11434/api/chat"
    sys_prompt = (
        "You are a QA Analyst reviewing a tele-call transcript conducted by Nandita, an AI sales agent. "
        "Analyze the conversation from the CUSTOMER's perspective and return:\n"
        "- summary: 1-2 sentence description of how the call went\n"
        "- lead_score: integer 0-10 (0=hostile/hung up, 5=neutral, 10=ready to buy)\n"
        "- final_intent: MUST be exactly one of: 'Interested', 'Not Interested', 'Neutral'\n\n"
        "SCORING GUIDE:\n"
        "- Score 0-3: Customer said no, hung up, was rude, or showed clear disinterest\n"
        "- Score 4-6: Customer was polite but non-committal or asked general questions\n"
        "- Score 7-9: Customer asked about pricing, features, or expressed genuine interest\n"
        "- Score 10: Customer agreed to a next step, demo, or purchase\n\n"
        "Output ONLY a pure JSON object, no markdown:\n"
        "{\"summary\": \"...\", \"lead_score\": 5, \"final_intent\": \"Neutral\"}"
    )
    tx_str = "\n".join([
        f"{msg.get('role', '').upper()}: {msg.get('content', '')}"
        for msg in transcript
    ])
    payload = {
        "model": "llama3.2:latest",
        "messages": [
            {"role": "system", "content": sys_prompt},
            {"role": "user", "content": f"Transcript:\n{tx_str}"}
        ],
        "stream": False,
        "temperature": 0.1
    }
    try:
        response = requests.post(url, json=payload, timeout=60)
        if response.status_code == 200:
            result_text = response.json().get('message', {}).get('content', '')
            match = re.search(r'\{.*\}', result_text, re.DOTALL)
            if match:
                try:
                    data = json.loads(match.group(0))
                    return {
                        "summary": data.get("summary", "No summary provided"),
                        "lead_score": data.get("lead_score", 0),
                        "final_intent": data.get("final_intent", "Neutral")
                    }
                except Exception:
                    pass
        return {"summary": "Could not parse scoring response", "lead_score": 0, "final_intent": "Neutral"}
    except Exception as e:
        return {"summary": f"Scoring error: {e}", "lead_score": 0, "final_intent": "Neutral"}
